services:
  postgres:
    image: postgres:15
    container_name: wiki_postgres
    environment:
      POSTGRES_DB: wiki_db
      POSTGRES_USER: wiki_user
      POSTGRES_PASSWORD: wiki_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiki_user -d wiki_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: wiki_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wiki_db
      - DB_USER=wiki_user
      - DB_PASSWORD=wiki_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: