version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wiki_postgres
    environment:
      POSTGRES_DB: wiki_db
      POSTGRES_USER: wiki_user
      POSTGRES_PASSWORD: wiki_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: wiki_app
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=wiki_db
      - DB_USER=wiki_user
      - DB_PASSWORD=wiki_password
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: